get:
  tags:
    - Rutas
  summary: Retorna el listado de rutas
  description: |
    Retorna el listado de rutas
    ### Filtros
    Se puede filtrar por: tipo
  security:
    - bearerToken: []
  parameters:
    - in: query
      name: type
      required: false
      schema:
        type: string
        enum: [ALL, WEB, MOBILE]
      description: "Filtra resultados por tipo"
  responses:
    200:
      description: Listado de rutas
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#components/schemas/Route"
    401:
      $ref: "#components/responses/401Unauthorized"
    403:
      $ref: "#components/responses/403Forbidden"
    404:
      $ref: "#components/responses/404NotFound"
    
  