openapi: "3.0.2"
info:
  title: Documentación API
  version: "1.0"
servers:
  - url: http://localhost:8080/

paths:
  $ref: "./paths/_index.yml"

components:
  schemas:
    $ref: "./components/schemas/_index.yml"
  securitySchemes:
    bearerToken:
      description: "Token de acceso, se puede generar en /login"
      type: http
      scheme: bearer
      bearerFormat: JWT
  requestBodies:
    $ref: "./components/requestBodies/_index.yml"
  responses:
    401Unauthorized:
      description: "No autenticado"
      content:
        application/json:
          schema:
            $ref: "#components/schemas/ErrorResponse"
          examples:
            no_token:
              summary: No se envió un token válido
              value:
                errors:
                  - "Unautorized"
            credentials:
              summary: Token expirado
              value:
                errors:
                  - expired token
            disabled:
              summary: Usuario desactivado
              value:
                errors:
                  - Usuario desactivado.
    403Forbidden:
      description: "Prohibido"
      content:
        application/json:
          schema:
            $ref: "#components/schemas/ErrorResponse"
          examples:
            forbidden:
              summary: Sin permisos para realizar esta acción
              value:
                errors:
                  - "No tienes permisos para realizar esta acción"
    404NotFound:
      description: "Recurso no encontrado"
      content:
        application/json:
          schema:
            $ref: "#components/schemas/ErrorResponse"
          examples:
            not_found:
              summary: No se encontraron resultados que coincidan con los parametros de busqueda
              value:
                errors:
                  - "No se encontraron registros"
    400BadRequest:
      description: "La petición no se pudo procesar, falta uno o más parámetros o los parametros son inválidos"
      content:
        application/json:
          schema:
            $ref: "#components/schemas/ErrorResponse"
          examples:
            request_parameters:
              summary: Faltan parámetros en el request
              value:
                errors:
                  - El campo x es obligatorio.
            path_parameters:
              summary: Id inválido
              value:
                errors:
                  - No existe un registro con el id enviado.
